/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Adress: typeof import('./components/Adress.vue')['default']
    Choice: typeof import('./components/Choice.vue')['default']
    Contact: typeof import('./components/Contact.vue')['default']
    Offer: typeof import('./components/Offer.vue')['default']
    Payment: typeof import('./components/Payment.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
